import re
from urllib.parse import urlparse


class HeuristicTextClassifier:
    def __init__(self):
        # Mappa semantica: keyword/pattern → label
        self.domain_map = {
            "medical": [
                "medico",
                "ospedale",
                "salute",
                "chirurgia",
                "terapia",
                "farmaco",
                "diagnosi",
                "paziente",
                "infermiere",
                "vaccino",
                "malattia",
                "cura",
                "ricovero",
                "trattamento",
                "emergenza",
                "pronto soccorso",
                "analisi",
                "visita",
                "medicina",
                "ambulatorio",
                "specialista",
                "anestesista",
                "cardiologo",
                "radiografia",
                "epidemia",
                "pandemia",
                "influenza",
                "oncologia",
                "psichiatria",
                "allergia",
                "dermatologia",
                "ginecologia",
                "pediatria",
            ],
            "legal": [
                "tribunale",
                "giudice",
                "sentenza",
                "processo",
                "reato",
                "avvocato",
                "penale",
                "civile",
                "giustizia",
                "legge",
                "costituzione",
                "difesa",
                "accusa",
                "condanna",
                "assoluzione",
                "testimone",
                "prova",
                "giuria",
                "arresto",
                "carcere",
                "giurisdizione",
                "ordinanza",
                "appello",
                "indagine",
                "inchiesta",
                "normativa",
                "codice",
                "violazione",
                "imputato",
                "autorità",
            ],
            "finance": [
                "borsa",
                "azioni",
                "titoli",
                "finanza",
                "mercato",
                "investimento",
                "economia",
                "credito",
                "debito",
                "banca",
                "interesse",
                "spread",
                "obbligazioni",
                "pil",
                "recessione",
                "fondo",
                "valuta",
                "moneta",
                "trading",
                "bilancio",
                "utile",
                "perdita",
                "profitto",
                "dividendo",
                "inflazione",
                "deflazione",
                "mutuo",
                "prestito",
                "tesoro",
                "indice",
            ],
            "sports": [
                "calcio",
                "basket",
                "tennis",
                "atletica",
                "olimpiadi",
                "partita",
                "campionato",
                "allenatore",
                "giocatore",
                "gol",
                "pallone",
                "arbitro",
                "torneo",
                "classifica",
                "gara",
                "pista",
                "record",
                "match",
                "boxe",
                "nuoto",
                "sci",
                "corsa",
                "bicicletta",
                "maratona",
                "rugby",
                "volley",
                "pallavolo",
                "vittoria",
                "sconfitta",
                "competizione",
            ],
            "culture": [
                "arte",
                "musica",
                "cinema",
                "letteratura",
                "teatro",
                "spettacolo",
                "pittura",
                "scultura",
                "opera",
                "artista",
                "romanzo",
                "film",
                "poesia",
                "scrittore",
                "regista",
                "attore",
                "attrice",
                "festival",
                "danza",
                "mostra",
                "classica",
                "moderna",
                "contemporanea",
                "critica",
                "libro",
                "fotografia",
                "fumetto",
                "dramma",
                "tragedia",
                "cultura",
            ],
            "crime": [
                "omicidio",
                "furto",
                "rapina",
                "assassinio",
                "criminale",
                "delitto",
                "truffa",
                "droga",
                "spaccio",
                "estorsione",
                "sequestro",
                "violenza",
                "arma",
                "omicida",
                "mafioso",
                "clan",
                "carcere",
                "aggressione",
                "criminalità",
                "indagato",
                "latitante",
                "denuncia",
                "polizia",
                "arresto",
                "colpevole",
                "incendio",
                "reato",
                "testimone",
                "investigazione",
                "omicidi",
            ],
            "world": [
                "geopolitica",
                "diplomazia",
                "nazioni",
                "governo",
                "presidente",
                "conflitto",
                "alleanza",
                "estero",
                "ambasciata",
                "sanzione",
                "accordo",
                "trattato",
                "crisi",
                "militare",
                "esercito",
                "guerra",
                "pace",
                "nato",
                "onu",
                "ue",
                "asia",
                "africa",
                "america",
                "europa",
                "medio oriente",
                "russia",
                "cina",
                "usa",
                "ucraina",
                "israele",
            ],
            "news": [
                "notizia",
                "evento",
                "cronaca",
                "attualità",
                "giornale",
                "intervista",
                "inchiesta",
                "reportage",
                "titolo",
                "redazione",
                "comunicato",
                "emergenza",
                "diretta",
                "edizione",
                "telegiornale",
                "annuncio",
                "pubblicazione",
                "editoriale",
                "cronista",
                "breaking",
                "informazione",
                "fatto",
                "ultimo",
                "titoli",
                "media",
                "cronache",
                "report",
                "notiziario",
                "corrispondenza",
                "fonte",
            ],
            "history": [
                "storia",
                "medioevo",
                "antica roma",
                "rivoluzione",
                "impero romano",
                "seconda guerra mondiale",
                "primo conflitto",
                "colonizzazione",
                "rinascimento",
                "antico egitto",
                "guerra fredda",
                "unificazione",
                "monarchia",
                "rivolta",
                "papi",
                "crociate",
                "epoca",
                "medievale",
                "antico",
                "risorgimento",
                "imperatore",
                "archeologia",
                "manoscritto",
                "cronaca",
                "periodo storico",
                "dinastia",
                "cronologie",
                "fonti storiche",
                "paleografia",
            ],
            "science": [
                "scienza",
                "esperimento",
                "ricerca",
                "fisica",
                "chimica",
                "biologia",
                "laboratorio",
                "teoria",
                "genetica",
                "atomo",
                "energia",
                "universo",
                "microscopio",
                "particelle",
                "scientifico",
                "osservazione",
                "astrofisica",
                "materia",
                "elettrone",
                "cervello",
                "neuronale",
                "protoni",
                "modello scientifico",
                "sperimentazione",
                "dati scientifici",
                "ipotesi",
                "evoluzione",
                "molecola",
                "DNA",
                "biochimica",
            ],
            "grammar": [
                "sintassi",
                "analisi grammaticale",
                "verbi",
                "aggettivi",
                "soggetto",
                "predicato",
                "complemento",
                "congiunzioni",
                "avverbi",
                "preposizioni",
                "morfologia",
                "declinazioni",
                "flessione",
                "coniugazioni",
                "analisi logica",
                "articoli",
                "pronomi",
                "forme verbali",
                "modi verbali",
                "tempi verbali",
                "sintagma",
                "costruzione",
                "frase semplice",
                "frase complessa",
                "grammatica italiana",
                "vocabolario",
                "ortografia",
                "semantica",
                "lessico",
                "linguistica",
            ],
            "literature": [
                "romanzo",
                "narrativa",
                "poesia",
                "racconto",
                "autore",
                "libro",
                "personaggio",
                "scrittura",
                "narrazione",
                "paragrafi",
                "capitolo",
                "trama",
                "metafora",
                "simbolismo",
                "protagonista",
                "poeta",
                "scrittore",
                "opera letteraria",
                "stile narrativo",
                "dramma",
                "commedia",
                "letteratura italiana",
                "critica letteraria",
                "classici",
                "lettura",
                "racconto breve",
                "versi",
                "epica",
                "letterario",
                "retorica",
            ],
            "religion": [
                "dio",
                "cristianesimo",
                "religione",
                "bibbia",
                "papa",
                "vangelo",
                "chiesa",
                "prete",
                "fede",
                "teologia",
                "sacerdote",
                "spiritualità",
                "messa",
                "preghiera",
                "cristo",
                "ebraismo",
                "islam",
                "corano",
                "santo",
                "sacramenti",
                "liturgia",
                "catechismo",
                "confessione",
                "miracolo",
                "anima",
                "vangeli",
                "vangelo",
                "paradiso",
                "inferno",
                "creazione",
            ],
            "education": [
                "scuola",
                "lezione",
                "insegnante",
                "alunno",
                "studente",
                "professore",
                "classe",
                "programma scolastico",
                "istruzione",
                "educazione",
                "compiti",
                "registro",
                "valutazione",
                "materie scolastiche",
                "curriculum",
                "apprendimento",
                "formazione",
                "diploma",
                "università",
                "esame",
                "docente",
                "educatore",
                "didattica",
                "pedagogia",
                "studiare",
                "libro di testo",
                "insegnamento",
                "compito in classe",
                "scuola media",
                "scuola superiore",
            ],
            "philosophy": [
                "filosofia",
                "pensiero",
                "aristotele",
                "kant",
                "plato",
                "socrate",
                "esistenzialismo",
                "ragione",
                "logos",
                "etica",
                "logica",
                "ontologia",
                "metafisica",
                "filosofo",
                "stoicismo",
                "idealismo",
                "marx",
                "cartesio",
                "nietzsche",
                "ermeneutica",
                "concetto",
                "epistemologia",
                "coscienza",
                "valore",
                "verità",
                "libertà",
                "anima",
                "morale",
                "critica",
                "dialettica",
            ],
            "fantasy": [
                "draghi",
                "magia",
                "spade",
                "castelli",
                "incantesimi",
                "regni",
                "elfi",
                "nani",
                "mago",
                "stregone",
                "avventura",
                "guerre epiche",
                "foresta incantata",
                "portale",
                "orchi",
                "mostri",
                "medaglione",
                "profeta",
                "profetia",
                "reame",
                "tenebre",
                "luce",
                "eroe",
                "malvagio",
                "trono",
                "spada magica",
                "cristallo",
                "armatura",
                "pozioni",
                "gilda",
            ],
            "tech": [
                "intelligenza artificiale",
                "tecnologia",
                "software",
                "app",
                "computer",
                "informatica",
                "programmazione",
                "algoritmi",
                "cloud",
                "cybersecurity",
                "internet",
                "sistema operativo",
                "hardware",
                "data",
                "machine learning",
                "deep learning",
                "neural network",
                "digitale",
                "blockchain",
                "metaverso",
                "robot",
                "automazione",
                "coding",
                "smartphone",
                "tecnologie emergenti",
                "sviluppo",
                "AI",
                "bot",
                "GPU",
                "quantistica",
            ],
            "mythology": [
                "mitologia",
                "zeus",
                "poseidone",
                "miti",
                "leggenda",
                "eroe",
                "titani",
                "olimpio",
                "dea",
                "oracolo",
                "fato",
                "achille",
                "ulisse",
                "giove",
                "apollo",
                "vulcano",
                "mito greco",
                "mito romano",
                "divinità",
                "pantheon",
                "ermes",
                "odissea",
                "eneide",
                "teseo",
                "era",
                "aracne",
                "narciso",
                "medusa",
                "storia mitologica",
                "favola",
            ],
            "nature": [
                "foresta",
                "animali",
                "ambiente",
                "natura",
                "clima",
                "ecosistema",
                "montagna",
                "mare",
                "oceano",
                "fiumi",
                "piante",
                "biodiversità",
                "deserto",
                "ghiaccio",
                "riscaldamento globale",
                "inquinamento",
                "fauna",
                "flora",
                "bosco",
                "vulcano",
                "geologia",
                "scienze naturali",
                "cielo",
                "tempo atmosferico",
                "ambiente naturale",
                "agricoltura",
                "energia rinnovabile",
                "alberi",
                "risorse naturali",
                "cambiamento climatico",
            ],
            "narrative": [
                "personaggio",
                "storia",
                "trama",
                "ambientazione",
                "conflitto",
                "narrazione",
                "voce narrante",
                "incipit",
                "finale",
                "climax",
                "flashback",
                "racconto",
                "descrizione",
                "dialogo",
                "tema",
                "sottotrama",
                "suspense",
                "punto di vista",
                "narrativa",
                "ritmo",
                "struttura",
                "sequenza",
                "scena",
                "episodio",
                "tensione",
                "prologo",
                "epilogo",
                "arco narrativo",
                "protagonista",
                "antagonista",
            ],
            "book": [
                "libro",
                "copertina",
                "autore",
                "capitolo",
                "editore",
                "biblioteca",
                "volume",
                "ISBN",
                "collana",
                "prefazione",
                "nota dell'autore",
                "pagina",
                "rilegatura",
                "scrittura",
                "lettura",
                "romanzo",
                "saggio",
                "pubblicazione",
                "pubblicato",
                "titolo",
                "recensione",
                "libreria",
                "ebook",
                "best seller",
                "genere",
                "premio letterario",
                "disponibile",
                "libretto",
                "raccolta",
                "manuale",
            ],
        }

    def classify(self, text: str, title: str = "", url: str = "") -> dict:
        scores = {}
        reason_map = {}

        content = f"{title.lower()} {text.lower()}"
        content = re.sub(r"[^\w\s]", "", content)

        # Analizza anche lo slug dell'URL
        url_path = urlparse(url).path.lower()

        for label, keywords in self.domain_map.items():
            score = 0
            matched = []
            for kw in keywords:
                if kw in content:
                    score += 0.4
                    matched.append(kw)
                if kw in title:
                    score += 0.3
                if f"/{kw}/" in url_path or kw in url_path:
                    score += 0.3
            if score > 0:
                scores[label] = score
                reason_map[label] = matched

        if not scores:
            return {
                "label": "unknown",
                "score": 0.0,
                "reason": "Nessuna keyword corrispondente trovata.",
            }

        best_label = max(scores, key=scores.get)
        return {
            "label": best_label,
            "score": round(scores[best_label], 3),
            "reason": f"Matched keywords: {reason_map[best_label]}",
        }
